config/routes.rb
Rails.application.routes.draw do
  root :to => 'books#top'

  get 'books' => 'books#index'

  get 'books/:id' => 'books#show',as:'book'

  get 'books/:id/edit' => 'books#edit',as:'edit_book'

  patch 'books/:id' => 'books#update', as: 'update_book'

  post 'books' => 'books#create'

  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, {presence: true}
  validates :body, {presence: true}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
  	  @books = Book.all.order(id: :asc)
  	  @book = Book.new
  end

  def create
  	  @book = Book.new(book_params)
      if @book.save
  	     redirect_to book_path(@book.id)
         flash[:notice] = "Book was successfully created."
      else
        @books = Book.all.order(id: :asc)
        render :index
      end

  end

  def show
  	  @book = Book.find(params[:id])
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
  	  @book = Book.find(params[:id])
  	  if @book.update(book_params)
  	     redirect_to book_path(@book.id)
         flash[:hoge] = "Book was successfully updated."
      else
         redirect_to("/books/#{@book.id}/edit")

      end
  end
  def destroy
        book = Book.find(params[:id])
        book.destroy
        flash[:success] = "Book was successfully destroyed."
        redirect_to books_path

  end


  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
  <% if @book && @book.errors.any? %>
   <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this obj from being saved:<br></h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
      <% end %>
    </ul>
   </div>


<div class="successfully">
  <% if flash[:update] %>
  <%= flash[:update] %>
  <% end %>
</div>



<h1>Editing Book</h1>
    <%= form_for(@book) do |f| %>
    <div class="field">
      <label for>Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <label for>Body</label>
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <a> </a>
      <%= f.submit 'Update Book' %>
    </div>
    <% end %>

    <a><%= link_to "Show", book_path(@book.id) %>
      |
    <a href="/books">Back</a>

app/views/books/index.html.erb
<html>
<head>
  <meta charset="UTF-8">
  <title>Bookers</title>
</head>

<body>

<div class="successfully">
<%= flash[:success] %>
</div>

<table>
  <thead>
    <h1>Books</h1>
     <tr>
       <th>Title</th>
       <th>Body</th>
       <th colspan="3"></th>
     </tr>
  </thead>

  <tbody>
      <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to "Show",book_path(book) %></td>
      <td><%= link_to "Edit",edit_book_path(book) %></td>
      <td><%= link_to "Destroy", destroy_book_path(book), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
      <% end %>
   </tbody>
 </table>

  
<h2>New book</h2>
   <% if @book && @book.errors.any? %>
   <div id="error_explanation">
       <h2><%= @book.errors.count %>errors prohibited this obj from being saved:<br></h2>
     <ul>
       <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
       <% end %>
       <% end %>
     </ul>
   </div>

<%= form_for(@book) do |f| %>


    <div class="field">
      <label for>Title</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <label for>Body</label>
      <%= f.text_area :body %>
    </div>

    <div cladd="actions">
      <a> </a>
      <%= f.submit 'Create Book' %>
    </div>
<% end %>

</body>
</html>

app/views/books/show.html.erb
<div class="successfully">
  <% if flash[:notice] %>
  <%= flash[:notice]%>
  <% end %>
</div>


<div class="successfully">
  <% if flash[:hoge] %>
  <%= flash[:hoge] %>
  <% end %>
</div>



<body>
<p><strong>Title: </strong><%= @book.title %></p>
<p><strong>Body: </strong><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id) %>
|
<a href="/books">Back</a>

</body>

app/views/books/top.html.erb
<head>
	<meta charset="utf-8">
	<title>Bookers</title>
</head>

<body>
 <h1>ようこそ <b>Bookers</b> へ！</h1>

  <p>
  	<b>Bookers</b>
  	では、さまざまな書籍に関するあなたの意見や
  </p>
  <p>
  印象を共有し交換することができます
  </p>

  <p><%= link_to "start",books_path %></p>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>